### ISSUE TITLE
Where to find 5x8 file?

### ISSUE THREAD

**Issue by wetfeet2000** [open-source-economics/taxdata#130]
Hi everyone, I'm a complete newbie to this taxdata repo and was hoping to just build an instance of puf.csv for the taxcalc library to try and reproduce the basic tutorial. I got the taxdata repo lodaed up, but when running `taxdata/puf_data/StatMatch/Matching/runmatch.py` I got a missing file error for `asec2014_pubuse_tax_fix_5x8.dat` . After some time on Google I found the following URL, https://thedataweb.rm.census.gov/pub/cps/march/asec2014_pubuse_tax_fix_5x8.zip , which is now resulting in a 404. It looks like some of the underlying data is coming from http://ceprdata.org/cps-uniform-data-extracts/march-cps-supplement/march-cps-data/ but those files don't appear to be compatible with runmatch.py. Any suggestions on where to find this data?

**Comment by MattHJensen** [comment]
@wetfeet2000, welcome!  

The `puf.csv` file relies on a copy of the IRS SOI public use file, which costs >$8k from IRS. Alternatively, there is a publicly-distributable file, `cps.csv`, that comes packaged with taxcalc. If you don't have access to the IRS PUF, then I recommend working with the `cps.csv` file instead, and there is no need to build it from scratch because it is already in taxcalc.

**Comment by wetfeet2000** [comment]
Thanks for your response @MattHJensen ! After some more playing around I got Tax-Calculator to build from scratch using Anaconda Python 3.6, unzipped the cps.csv.gz, and was able to go through the tutorial using the TC CLI using cps.csv no problem. Interestingly, when I use cps.csv in the "10_Minutes_to_Tax-Calculator.ipynb" file, I get this error:
```
(C:\Users\wetfeet2000\AppData\Local\Continuum\miniconda3) C:\Users\wetfeet2000\git\Tax-Calculator>python
Python 3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from taxcalc import *
>>> # The baseline includes AMT repeal.
... p_xx = Policy()
>>> reform_xx = {
...     2017: {
...         '_AMT_rt1': [0.0],
...         '_AMT_rt2': [0.0]
...     }
... }
>>> p_xx.implement_reform(reform_xx)
>>>
>>> # The reform expands the second tax bracket
... # (and repeals AMT to match the baseline)
...
>>> p_yy = Policy()
>>> reform_yy = {
...     2017: {
...         '_II_brk2': [[65005, 130010, 65005, 88180, 0]],
...         '_AMT_rt1': [0.0],
...         '_AMT_rt2': [0.0]
...     }
... }
>>> p_yy.implement_reform(reform_yy)
>>> c_xx = Calculator(policy=p_xx, records=Records("taxcalc\cps.csv"))
Traceback (most recent call last):
  File "C:\Users\wetfeet2000\AppData\Local\Continuum\miniconda3\lib\site-packages\pandas\core\indexing.py", line 1794, in _get_list_axis
    return self.obj._take(key, axis=axis, convert=False)
  File "C:\Users\wetfeet2000\AppData\Local\Continuum\miniconda3\lib\site-packages\pandas\core\generic.py", line 2150, in _take
    verify=True)
  File "C:\Users\wetfeet2000\AppData\Local\Continuum\miniconda3\lib\site-packages\pandas\core\internals.py", line 4250, in take
    indexer = maybe_convert_indices(indexer, n)
  File "C:\Users\wetfeet2000\AppData\Local\Continuum\miniconda3\lib\site-packages\pandas\core\indexing.py", line 2103, in maybe_convert_indices
    raise IndexError("indices are out-of-bounds")
IndexError: indices are out-of-bounds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wetfeet2000\git\Tax-Calculator\taxcalc\records.py", line 153, in __init__
    self.WT = self.WT.iloc[self.index]
  File "C:\Users\wetfeet2000\AppData\Local\Continuum\miniconda3\lib\site-packages\pandas\core\indexing.py", line 1373, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Users\wetfeet2000\AppData\Local\Continuum\miniconda3\lib\site-packages\pandas\core\indexing.py", line 1819, in _getitem_axis
    return self._get_list_axis(key, axis=axis)
  File "C:\Users\wetfeet2000\AppData\Local\Continuum\miniconda3\lib\site-packages\pandas\core\indexing.py", line 1797, in _get_list_axis
    raise IndexError("positional indexers are out-of-bounds")
IndexError: positional indexers are out-of-bounds
>>>
```

This seems more an issue for the Tax-Calculator repo rather than here, but I figured you might want to be aware. (I'm not sure if its possible to move an issue from one repo to another in Github) 

Below is the build log from conda showing the dependency versions:
```
    bokeh:           0.12.10-py36h0be3b39_0
    icc_rt:          2017.0.4-h97af966_0
    intel-openmp:    2018.0.0-hd92c6cd_8
    llvmlite:        0.20.0-py36_0
    mkl:             2018.0.1-h2108138_4
    numba:           0.35.0-np113py36_10
    numpy:           1.13.3-py36ha320f96_0
    pandas:          0.21.0-py36he09d4dd_1
    python-dateutil: 2.6.1-py36h509ddcb_1
    pytz:            2017.3-py36h1d3fa6b_0
    taxcalc:         0.0.0-py36_0           local
    toolz:           0.8.2-py36he152a52_0
    tornado:         4.5.2-py36h57f6048_0
```

**Comment by wetfeet2000** [comment]
OK, I "tried harder" and got it. For anyone else out there having the same issue, here is the syntax needed to get the 10_Minutes_to_Tax-Calculator.ipynb tutorial working with cps.csv:
```
(C:\Users\wetfeet2000\AppData\Local\Continuum\miniconda3) C:\Users\wetfeet2000\git\Tax-Calculator>python
Python 3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from taxcalc import *
>>> # The baseline includes AMT repeal.
... p_xx = Policy()
>>> reform_xx = {
...     2017: {
...         '_AMT_rt1': [0.0],
...         '_AMT_rt2': [0.0]
...     }
... }
>>> p_xx.implement_reform(reform_xx)
>>>
>>> # The reform expands the second tax bracket
... # (and repeals AMT to match the baseline)
...
>>> p_yy = Policy()
>>> reform_yy = {
...     2017: {
...         '_II_brk2': [[65005, 130010, 65005, 88180, 0]],
...         '_AMT_rt1': [0.0],
...         '_AMT_rt2': [0.0]
...     }
... }
>>> p_yy.implement_reform(reform_yy)
>>> c_xx = Calculator(policy=p_xx, records=Records("taxcalc\cps.csv", weights='taxcalc\cps_weights.csv', start_year=2014))
You loaded data for 2014.
Tax-Calculator startup automatically extrapolated your data to 2014.
>>> c_yy = Calculator(policy=p_yy, records=Records("taxcalc\cps.csv", weights='taxcalc\cps_weights.csv', start_year=2014))
You loaded data for 2014.
Tax-Calculator startup automatically extrapolated your data to 2014.
>>> c_xx.advance_to_year(2017)
>>> c_yy.advance_to_year(2017)
>>> assert c_xx.current_year == 2017
>>> assert c_yy.current_year == 2017
>>> c_xx.calc_all()
>>> c_yy.calc_all()
>>> ((c_yy.records.combined - c_xx.records.combined)*c_xx.records.s006).sum()
-96121372496.544403
>>>
```
