### ISSUE TITLE
"FileNotFoundError: File b'cps-matched-puf.csv' does not exist"

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [open-source-economics/taxdata#134]
I cloned the [Tax Calculator repo](https://github.com/open-source-economics/Tax-Calculator) and created the taxcalc-dev conda environment as described [here](http://taxcalc.readthedocs.io/en/latest/contributor_guide.html). I activated that conda environment and running all the tests, validation and otherwise (they all succeeded after a little tweaking). Then, still in the conda environment, I tried to generate a sample data file from a clone of this repo, taxdata, by running `./csvmake puf 1`. I receive the following stack trace and messages:

```
(taxcalc-dev) jeff@jbb-lenovo:~/javeriana/taxdata$ ./csvmake puf 1
Wed Dec  6 16:03:12 -05 2017 : puf_data START
Traceback (most recent call last):
  File "finalprep.py", line 555, in <module>
    sys.exit(main())
  File "finalprep.py", line 15, in main
    data = pandas.read_csv('cps-matched-puf.csv')
  File "/home/jeff/installs/miniconda3/envs/taxcalc-dev/lib/python3.5/site-packages/pandas/io/parsers.py", line 705, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/jeff/installs/miniconda3/envs/taxcalc-dev/lib/python3.5/site-packages/pandas/io/parsers.py", line 445, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/jeff/installs/miniconda3/envs/taxcalc-dev/lib/python3.5/site-packages/pandas/io/parsers.py", line 814, in __init__
    self._make_engine(self.engine)
  File "/home/jeff/installs/miniconda3/envs/taxcalc-dev/lib/python3.5/site-packages/pandas/io/parsers.py", line 1045, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/jeff/installs/miniconda3/envs/taxcalc-dev/lib/python3.5/site-packages/pandas/io/parsers.py", line 1684, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 391, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 710, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'cps-matched-puf.csv' does not exist
ERROR: executing /finalprep.py script
NO 'git diff' OUTPUT ==> NO CHANGES IN FILES
(taxcalc-dev) jeff@jbb-lenovo:~/javeriana/taxdata$
```

I find no file named anything like that, in either the Tax-Calculator or taxdata repos:
```
(taxcalc-dev) jeff@jbb-lenovo:~/javeriana$ ls
Tax-Calculator  taxdata
(taxcalc-dev) jeff@jbb-lenovo:~/javeriana$ find . -name "*matched*.csv"
(taxcalc-dev) jeff@jbb-lenovo:~/javeriana$ 
```

**Comment by Amy-Xu** [comment]
Hmmmmm that cps-matched-puf is actually a file based on the public use file from IRS. It's a proprietary file. By any chance you have gained access to that file from IRS? Alternatively you can try the cps tax unit database in the Tax-Calculator.
