### ISSUE TITLE
conda package inconsistency

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/taxdata#20]
In the taxdata repository, I tried to execute the `final_prep\puf-cps-processing.py` script on my computer.
Here is the error message I got:
```
iMac2:final prep mrh$ python puf-cps-processing.py cps-puf-2016-04-27.csv
Traceback (most recent call last):
  File "puf-cps-processing.py", line 211, in <module>
    sys.exit(main())
  File "puf-cps-processing.py", line 47, in main
    data = create_new_recid(data)
  File "puf-cps-processing.py", line 73, in create_new_recid
    sorted_dta = data.sort_values(by='recid')
  File "/Users/mrh/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 2150, in __getattr__
    (type(self).__name__, name))
AttributeError: 'DataFrame' object has no attribute 'sort_values'
```

Turns out I had pandas 16 installed and the DataFrame.sort_values() method was introduced in version 17.
```
iMac2:final prep mrh$ conda list | grep pandas
pandas                    0.16.2               np19py27_0    defaults
```

So, I upgraded pandas as follows:
```
iMac2:final prep mrh$ conda update pandas
Fetching package metadata: ....
Solving package specifications: .........

Package plan for installation in environment /Users/mrh/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.10.4               |           py27_0         3.0 MB
    numexpr-2.4.4              |      np110py27_0         103 KB
    scipy-0.16.0               |      np110py27_1        11.8 MB
    pandas-0.18.0              |      np110py27_0         5.8 MB
    scikit-learn-0.16.1        |      np110py27_0         3.3 MB
    ------------------------------------------------------------
                                           Total:        24.1 MB

The following packages will be UPDATED:

    numexpr:      2.4.3-np19py27_0  --> 2.4.4-np110py27_0 
    pandas:       0.16.2-np19py27_0 --> 0.18.0-np110py27_0
    scikit-learn: 0.16.1-np19py27_0 --> 0.16.1-np110py27_0
    scipy:        0.15.1-np19py27_0 --> 0.16.0-np110py27_1

The following packages will be DOWNGRADED:

    numpy:        1.11.0-py27_0     --> 1.10.4-py27_0     

Proceed ([y]/n)? y

Fetching packages ...
numpy-1.10.4-p 100% |################################| Time: 0:00:00   4.06 MB/s
numexpr-2.4.4- 100% |################################| Time: 0:00:00   1.60 MB/s
scipy-0.16.0-n 100% |################################| Time: 0:00:01   8.97 MB/s
pandas-0.18.0- 100% |################################| Time: 0:00:01   4.28 MB/s
scikit-learn-0 100% |################################| Time: 0:00:00   5.17 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
```

Then I tried again to execute the `puf-cps-processing.py` script and here is what I got:
```
iMac2:final prep mrh$ python puf-cps-processing.py cps-puf-2016-04-27.csv
/Users/mrh/anaconda/lib/python2.7/site-packages/pandas/computation/__init__.py:19: UserWarning: The installed version of numexpr 2.4.4 is not supported in pandas and will be not be used

  UserWarning)
```

So, I have two questions:

(1) Why does the Anaconda distribution have conflicting packages?  I asked for the newest pandas and  conda gave my (without asking) a version of numexpr that does not work with the version of pandas is supplied.  Isn't this a conda bug?

(2) How do I fix this problem?  I get this message every time I run the Tax-Calculator, which is very annoying, and maybe, dangerous.

@talumbau @MattHJensen @Amy-Xu

**Comment by talumbau** [comment]
This appears to be a `pandas` issue, as noted in the 0.18.0 release notes:

http://pandas.pydata.org/pandas-docs/version/0.18.0/whatsnew.html

May I ask, when did you perform this command? It's surprising to me that you did not get upgraded to the version of 0.18.0 pandas that was built for numpy 1.11 instead of numpy 1.10 (which is what happened). Anyway, the release notes for 0.18.0 of pandas and the Github issue link in the notes seem to indicate that you can update your numexpr and you won't get the message any more. So I would execute:

```
conda update numexpr
```

and you should be good to go. Please update the issue if that does not resolve the problem. Also, it seems we should update to pandas 0.18.0 for the Tax-Calculator release.

**Comment by martinholmer** [comment]
T.J. (@talumbau),  Thanks for the tip!  The command `conda update numexpr` fixed things.
