### ISSUE TITLE
Benefits extrapolation script does not work

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/taxdata#232]
On the tip of the master branch, I ran the `rename_columns.py` script successfully.
Then I changed the `extrapolation.py` script to read the CPS weights in the `cps_stage2/cps_weights.csv.gz` file and when I execute `python extrapolation.py` this is what I get:
```
iMac:cps_stage4 mrh$ python extrapolation.py 
('starting year', 2015)
extrapolation.py:148: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  result = pd.concat([noncandidates, candidates], axis=0, ignore_index=False)
('total time', 6.2189788818359375)
('ssi', 'this year total is ', 7526933, ', target is ', '7537656.678923858', ', diff is ', '-10723.67892385833', ',', '-0.0014226807323080859')
('total time', 4.664236068725586)
('mcaid', 'this year total is ', 56293352, ', target is ', '56364501.59841771', ', diff is ', '-71149.59841770679', ',', '-0.0012623122071517463')
('total time', 4.444383144378662)
('mcare', 'this year total is ', 50637924, ', target is ', '50662439.87755156', ', diff is ', '-24515.877551563084', ',', '-0.0004839063734556935')
('total time', 4.628061771392822)
('vet', 'this year total is ', 4917104, ', target is ', '4939167.070071559', ', diff is ', '-22063.0700715594', ',', '-0.004466961687781042')
('total time', 4.7146289348602295)
('snap', 'this year total is ', 42180559, ', target is ', '42189411.44151255', ', diff is ', '-8852.441512547433', ',', '-0.0002098261438138247')
('total time', 4.91064715385437)
('tanf', 'this year total is ', 2979556, ', target is ', '3001327.9533102163', ', diff is ', '-21771.95331021631', ',', '-0.0072541067317230855')
Traceback (most recent call last):
  File "extrapolation.py", line 264, in <module>
    ben.increment_year()
  File "extrapolation.py", line 45, in increment_year
    tol=tol)
  File "extrapolation.py", line 133, in _extrapolate
    atol=0.0, rtol=tol
AssertionError
```
What's going on?

**Comment by martinholmer** [comment]
@hdoupe and @andersonfrailey,  When was the last time somebody executed the `extrapolation.py` script?

**Comment by martinholmer** [comment]
Also, in addition to the bug in the benefit `extrapolation.py` script reported [here](https://github.com/open-source-economics/taxdata/issues/232#issue-334948640), this script generates many PEP8-style errors that would make it impossible to check-in this file to a repository that was enforcing this coding style (as, for example, the Tax-Calculator repository is):
```
iMac:cps_stage4 mrh$ pycodestyle extrapolation.py 
extrapolation.py:27:5: E303 too many blank lines (2)
extrapolation.py:32:80: E501 line too long (89 > 79 characters)
extrapolation.py:33:80: E501 line too long (81 > 79 characters)
extrapolation.py:118:50: E741 ambiguous variable name 'I'
extrapolation.py:124:53: E741 ambiguous variable name 'I'
extrapolation.py:128:50: E741 ambiguous variable name 'I'
extrapolation.py:130:53: E741 ambiguous variable name 'I'
extrapolation.py:164:40: E741 ambiguous variable name 'I'
extrapolation.py:165:80: E501 line too long (80 > 79 characters)
extrapolation.py:167:80: E501 line too long (83 > 79 characters)
extrapolation.py:172:9: E741 ambiguous variable name 'I'
extrapolation.py:229:80: E501 line too long (83 > 79 characters)
extrapolation.py:230:80: E501 line too long (81 > 79 characters)
extrapolation.py:235:80: E501 line too long (83 > 79 characters)
extrapolation.py:238:80: E501 line too long (81 > 79 characters)
extrapolation.py:240:80: E501 line too long (80 > 79 characters)
extrapolation.py:242:80: E501 line too long (94 > 79 characters)
extrapolation.py:245:13: E303 too many blank lines (2)
extrapolation.py:251:80: E501 line too long (84 > 79 characters)
extrapolation.py:258:80: E501 line too long (104 > 79 characters)
extrapolation.py:259:80: E501 line too long (83 > 79 characters)
extrapolation.py:261:80: E501 line too long (86 > 79 characters)
extrapolation.py:263:80: E501 line too long (88 > 79 characters)
extrapolation.py:264:80: E501 line too long (80 > 79 characters)
extrapolation.py:265:80: E501 line too long (92 > 79 characters)
extrapolation.py:266:80: E501 line too long (81 > 79 characters)
extrapolation.py:270:80: E501 line too long (96 > 79 characters)
extrapolation.py:271:80: E501 line too long (110 > 79 characters)
extrapolation.py:272:80: E501 line too long (105 > 79 characters)
extrapolation.py:273:80: E501 line too long (113 > 79 characters)
extrapolation.py:274:80: E501 line too long (105 > 79 characters)
extrapolation.py:275:80: E501 line too long (100 > 79 characters)
```

It also generates the following Pandas warning:
```
extrapolation.py:167: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  result = pd.concat([noncandidates, candidates], axis=0, ignore_index=False)
```
I don't know if this is a problem or not because it is not at all clear to me what whether sorting is desired or not.

@hdoupe @andersonfrailey @MattHJensen

**Comment by hdoupe** [comment]
I bumped the tolerance up from 1% to 5% and everything runs just fine. Could it be possible that the data has changed since this script was last run and this is what's breaking the script?

**Comment by martinholmer** [comment]
> 
> I bumped the tolerance up from 1% to 5% and everything runs just fine. Could it be possible that the data has changed since this script was last run and this is what's breaking the script?
> 

What do you mean by “the data”?
If 5% tolerance is OK now, why was 1% tolerance used originality?  Can you explain why there is a need for any positive tolerance?  Why would there ever be a shortage of participants to hit a target?

**Comment by Amy-Xu** [comment]
My intuition that we need a positive tolerance because, if I remember correctly, many individual weights in the low income range are quite large. So it's hard to hit the targets exactly.

In terms of the tolerance, I personally feel either 1% or 5% is fine with our purpose, but it might worth a bit time to figure out why exactly we have to increase the tolerance from 1% to 5%. The 5% tolerance doesn't sound too bothering, but just in case some sort of existing issues later on lead to another increase, say 10%. That would be a little bit too much in my mind.

**Comment by martinholmer** [comment]
@Amy-Xu said:
> My intuition that we need a positive tolerance because, if I remember correctly, many individual weights in the low income range are quite large. So it's hard to hit the targets exactly.

@Amy-Xu, thanks for your response, but I'm still confused.  If "it's hard to hit the targets exactly," why is there only one call to `np.allclose` in the `extrapolation.py` script?  Right now the script only determines whether or not we are close to the participant-count targets.  Don't we want to know by how much we miss the dollar-amount targets?

@hdoupe @andersonfrailey @MattHJensen

**Comment by MattHJensen** [comment]
I’d also be interested to know what tolerance is required for the participation numbers if they (participation numbers) are not explicitly targeted. I remember that the explicit participation targetting added some complexity and size to tax-calculator, and so while we are examining tolerances, it might be a useful exercise to compare the tolerance w explicit targeting to that w/o.

**Comment by hdoupe** [comment]
@martinholmer said:
> Thanks for your response, but I'm still confused. If "it's hard to hit the targets exactly," why is there only one call to np.allclose in the extrapolation.py script? Right now the script only determines whether or not we are close to the participant-count targets. Don't we want to know by how much we miss the dollar-amount targets?

Right now, the participant levels are the only targets that are hit. I'm unsure why the dollar amounts were not targeted. @Amy-Xu do you know why the dollar amounts were not targeted?

Right now, the difference between the actual and expected participant levels is the "distance" measure that we are minimizing:

We have a vector of participants `p` (p_i in {0, 1}, 0 if not participating, 1 if participating) sorted in descending order by probability of participating. Next find the cut-off index `i` to minimize `cumsum(p; i) - target_participants` where cumsum is sum from `i = 0 to i weight_i * p_i`. All people below the cutoff index are set as participants and all above the index are not set as participants.

This could be augmented to include the number of participants and the dollar amounts. For example you could minimize the distance between the two aggregates:

`dist(cumsum(p; i) - target_participants, cumsum(dollar_amount; i) - target_dollar_amount)`

One could run experiments with different distance metrics like the euclidean distance metric or the Mahalanobis distance metric.

Or, perhaps, a new approach could be considered that better considers multiple targets (only if hitting multiple targets is important).

However, I don't have very much background knowledge on this problem. So, please discount my suggestions accordingly.

**Comment by martinholmer** [comment]
@hdoupe, Thanks for your [detailed description](https://github.com/open-source-economics/taxdata/issues/232#issuecomment-402170864) of the current logic in the benefit `extrapolation.py` script.  By the way, your "background knowledge on this problem" is far more extensive than mine, and I think your suggestions about how to implement multiple-targeting sound promising.

However, this discussion has generated a [request](https://github.com/open-source-economics/taxdata/issues/232#issuecomment-401628935) from @MattHJensen to explore the pros and cons of simplifying the benefit extrapolation logic.  To my mind that is the first order of business.  Does anybody have an idea about how we can answer @MattHJensen's question?

@Amy-Xu @hdoupe @andersonfrailey @MattHJensen

**Comment by andersonfrailey** [comment]
@MattHJensen can you explain what you mean by using explicit targeting and not using explicit targeting?

**Comment by martinholmer** [comment]
@andersonfrailey asked @MattHJensen what he meant in issue #232 when he asked what the "participation numbers [would be] if they (participation numbers) are not explicitly targeted."  @MattHJensen will be able to give the definitive answer to your question, but my understanding is that he's asking how far off the participation numbers would be from their targets if we used the same benefit extrapolation logic that is used for other benefits and for all the other Tax-Calculator variables.  In other words, how different would benefit participant counts and targets be if we had a growfactor for each benefit (just like we have a growfactor for other benefits). 

@Amy-Xu @hdoupe

**Comment by Amy-Xu** [comment]
@MattHJensen asked

>I remember that the explicit participation targetting added some complexity and size to tax-calculator, and so while we are examining tolerances, it might be a useful exercise to compare the tolerance w explicit targeting to that w/o. @Amy-Xu, do you think this is a reasonable/doable thing to look at?

@andersonfrailey If I understand right, I think Matt refers to an alternative Martin proposed last year that we can do this extrapolation in a similar way as other tax variables. Specifically, we could just collect growth factors and apply them directly to the benefits without creating explicit targets. Both pros and cons were discussed in detail in issue #106. 

It could be worthwhile since it would significantly reduce the size of the CPS file, if that is a primary goal. If we were about to do the exercise, I would suggest to compare the benefit distribution by income, and the average benefit for each program.

**Comment by hdoupe** [comment]
Thanks for the info @Amy-Xu. Does this approach sound sensible:
- do the benefits extrapolation with the growth factors method
- compare the benefit distribution and average benefit for each program
- judge based off of these results whether the growth factors method or discrete choice (current) method is better/more efficient
